const ui=document.querySelector("#ui"),hud=document.querySelector("#hud"),scoreBox=document.querySelector("#scores");
let teams=[],active=-1,currentQ=null,angle=0,used=[];
const COLORS=["#e45f56","#e8ad3c","#50ad70","#4b9ec4","#8a69c7","#d86aa2","#53b7ac","#d47b42"];
const questions=[
{q:"สิ่งมีชีวิตใดเป็นผู้ผลิต?",a:"ต้นไม้",o:["ต้นไม้","กระต่าย","งู","เหยี่ยว"],e:"ต้นไม้สร้างอาหารเองได้โดยใช้พลังงานจากแสงอาทิตย์ จึงเป็นผู้ผลิต"},
{q:"สิ่งมีชีวิตใดเป็นผู้บริโภค?",a:"กระต่าย",o:["หญ้า","สาหร่าย","ต้นไม้","กระต่าย"],e:"กระต่ายสร้างอาหารเองไม่ได้และต้องกินพืช จึงเป็นผู้บริโภค"},
{q:"สิ่งใดแตกต่างจากพวก เพราะมีบทบาทในระบบนิเวศต่างกัน?",a:"กระต่าย",o:["ต้นไม้","หญ้า","สาหร่าย","กระต่าย"],e:"สามชนิดแรกเป็นผู้ผลิต ส่วนกระต่ายเป็นผู้บริโภค"},
{q:"สิ่งมีชีวิตใดสร้างอาหารเองได้?",a:"หญ้า",o:["กบ","งู","หญ้า","กระต่าย"],e:"หญ้าเป็นพืชและสังเคราะห์ด้วยแสงได้"},
{q:"สิ่งมีชีวิตใดต้องกินสิ่งมีชีวิตอื่นเพื่อให้ได้พลังงาน?",a:"กบ",o:["ต้นไม้","หญ้า","สาหร่าย","กบ"],e:"กบเป็นผู้บริโภค จึงต้องกินสิ่งมีชีวิตอื่น"},
{q:"กระต่ายกินหญ้า กระต่ายมีบทบาทใดในระบบนิเวศ?",a:"ผู้บริโภค",o:["ผู้ผลิต","ผู้บริโภค","ผู้ย่อยสลาย","ผู้บริโภคซาก"],e:"กระต่ายเป็นผู้บริโภค เพราะไม่สามารถสร้างอาหารเองและต้องกินพืชเป็นอาหาร"},
{q:"ผู้ผลิตในแหล่งน้ำคือข้อใด?",a:"สาหร่าย",o:["ปลา","กบ","งู","สาหร่าย"],e:"สาหร่ายสังเคราะห์ด้วยแสงได้ จึงเป็นผู้ผลิตในแหล่งน้ำ"},
{q:"ข้อใดไม่ใช่ผู้ผลิต?",a:"งู",o:["ต้นไม้","เฟิร์น","หญ้า","งู"],e:"งูสร้างอาหารเองไม่ได้ จึงเป็นผู้บริโภค"},
{q:"สิ่งใดแตกต่างจากอีกสามชนิด?",a:"เหยี่ยว",o:["ต้นไม้","หญ้า","สาหร่าย","เหยี่ยว"],e:"เหยี่ยวเป็นผู้บริโภค ส่วนอีกสามชนิดเป็นผู้ผลิต"},
{q:"ถ้าหญ้าลดลงมาก สัตว์ชนิดใดจะมีอาหารลดลงโดยตรง?",a:"กระต่าย",o:["กระต่าย","เหยี่ยว","งู","กบ"],e:"กระต่ายกินหญ้า จึงได้รับผลกระทบโดยตรงเมื่อหญ้าลดลง"},
{q:"ในห่วงโซ่ หญ้า → กระต่าย → งู สิ่งใดเป็นผู้ผลิต?",a:"หญ้า",o:["หญ้า","กระต่าย","งู","เหยี่ยว"],e:"หญ้าสร้างอาหารเองได้และเป็นจุดเริ่มต้นของห่วงโซ่อาหาร"},
{q:"ในห่วงโซ่ หญ้า → กระต่าย → งู ใครกินผู้ผลิตโดยตรง?",a:"กระต่าย",o:["กระต่าย","งู","เหยี่ยว","กบ"],e:"กระต่ายกินหญ้าซึ่งเป็นผู้ผลิตโดยตรง"},
{q:"ถ้ากระต่ายลดลงมาก งูที่กินกระต่ายมีแนวโน้มเป็นอย่างไร?",a:"จำนวนงูลดลง",o:["จำนวนงูลดลง","จำนวนงูเพิ่มขึ้น","จำนวนงูเท่าเดิมเสมอ","งูเปลี่ยนเป็นผู้ผลิต"],e:"งูมีอาหารลดลง จึงมีแนวโน้มลดจำนวนลง"},
{q:"ถ้างูลดลงมาก จำนวนกบซึ่งเป็นเหยื่อของงูมีแนวโน้มเป็นอย่างไร?",a:"จำนวนกบเพิ่มขึ้น",o:["จำนวนกบเพิ่มขึ้น","จำนวนกบลดลงทันที","กบเปลี่ยนเป็นผู้ผลิต","กบหยุดกินอาหาร"],e:"เมื่อผู้ล่าลดลง กบถูกล่าน้อยลง จึงมีแนวโน้มเพิ่มจำนวนขึ้น"},
{q:"ถ้ากระต่ายเพิ่มจำนวนมากเกินไป สิ่งใดอาจลดลง?",a:"หญ้า",o:["หญ้า","งู","เหยี่ยว","กบ"],e:"กระต่ายจำนวนมากกินหญ้ามากขึ้น ทำให้หญ้าอาจลดลง"},
{q:"ถ้าไม่มีแสงอาทิตย์ ผู้ผลิตจะได้รับผลกระทบอย่างไร?",a:"สร้างอาหารได้ยากขึ้น",o:["สร้างอาหารได้ยากขึ้น","สร้างอาหารได้มากขึ้น","เปลี่ยนเป็นผู้บริโภคทันที","ไม่มีผลต่อการสร้างอาหาร"],e:"ผู้ผลิตต้องใช้พลังงานแสงในการสังเคราะห์ด้วยแสง"},
{q:"ต้นไม้ หญ้า และสาหร่ายมีบทบาทเหมือนกันอย่างไร?",a:"เป็นผู้ผลิต",o:["เป็นผู้ผลิต","เป็นผู้บริโภค","เป็นผู้ย่อยสลาย","เป็นผู้บริโภคซาก"],e:"ทั้งต้นไม้ หญ้า และสาหร่ายสร้างอาหารเองได้ จึงเป็นผู้ผลิต"},
{q:"สัตว์ชนิดใดเป็นผู้บริโภคที่กินสัตว์อื่น?",a:"เหยี่ยว",o:["หญ้า","ต้นไม้","สาหร่าย","เหยี่ยว"],e:"เหยี่ยวล่าสัตว์อื่นเป็นอาหาร จึงเป็นผู้บริโภค"},
{q:"ถ้าผู้ผลิตในระบบนิเวศลดลงมาก ผลใดมีแนวโน้มเกิดขึ้น?",a:"ผู้บริโภคมีอาหารลดลง",o:["ผู้บริโภคมีอาหารลดลง","ผู้บริโภคมีอาหารเพิ่มขึ้น","พลังงานในระบบเพิ่มขึ้นทันที","ไม่มีสิ่งมีชีวิตใดได้รับผลกระทบ"],e:"ผู้ผลิตเป็นแหล่งพลังงานสำคัญ เมื่อผู้ผลิตลดลง ผู้บริโภคจึงมีอาหารและพลังงานลดลง"},
{q:"สิ่งใดนำพลังงานจากแสงอาทิตย์เข้าสู่ห่วงโซ่อาหาร?",a:"หญ้า",o:["งู","กบ","หญ้า","เหยี่ยว"],e:"หญ้าใช้แสงสร้างอาหาร พลังงานจึงเริ่มเข้าสู่ห่วงโซ่อาหารผ่านผู้ผลิต"},
{q:"ข้อใดเป็นผู้ผลิตทั้งหมด?",a:"ต้นไม้",o:["ต้นไม้","กระต่าย","กบ","งู"],e:"ต้นไม้เป็นผู้ผลิต ส่วนสัตว์เป็นผู้บริโภค"},
{q:"ถ้าต้นไม้ในป่าลดลงมาก สัตว์กินพืชมีแนวโน้มได้รับผลอย่างไร?",a:"อาหารและที่อยู่อาศัยลดลง",o:["อาหารและที่อยู่อาศัยลดลง","อาหารเพิ่มขึ้นทันที","กลายเป็นผู้ผลิต","ไม่เกิดผลกระทบใดเลย"],e:"ต้นไม้เป็นทั้งแหล่งอาหารและส่วนหนึ่งของที่อยู่อาศัยของสัตว์หลายชนิด"},
{q:"ข้อใดอธิบายความหมายของผู้บริโภคได้ถูกต้อง?",a:"สิ่งมีชีวิตที่ต้องกินสิ่งมีชีวิตอื่นเป็นอาหาร",o:["สิ่งมีชีวิตที่ต้องกินสิ่งมีชีวิตอื่นเป็นอาหาร","สิ่งมีชีวิตที่สร้างอาหารเองได้","สิ่งไม่มีชีวิตในระบบนิเวศ","สิ่งมีชีวิตที่ได้รับพลังงานจากแสงโดยตรงทุกชนิด"],e:"ผู้บริโภคสร้างอาหารเองไม่ได้ จึงต้องกินสิ่งมีชีวิตอื่นเพื่อรับพลังงาน"},
{q:"สิ่งใดแตกต่างจากพวก?",a:"ปลา",o:["หญ้า","ต้นไม้","สาหร่าย","ปลา"],e:"ปลาเป็นผู้บริโภค ส่วนอีกสามชนิดเป็นผู้ผลิต"}
];
function svg(name){
const V='viewBox="0 0 180 160"';
const shadow='<ellipse cx="90" cy="143" rx="60" ry="9" fill="#173e32" opacity=".35"/>';
if(name==="ต้นไม้"||name==="เฟิร์น")return `<svg ${V}>${shadow}<rect x="82" y="72" width="18" height="67" rx="8" fill="#815535"/><circle cx="91" cy="55" r="42" fill="#3e9851"/><circle cx="61" cy="66" r="28" fill="#57b867"/><circle cx="122" cy="68" r="30" fill="#318246"/><circle cx="77" cy="42" r="14" fill="#75cb76" opacity=".8"/></svg>`;
if(name==="หญ้า")return `<svg ${V}>${shadow}<g fill="#55b75a">${[42,58,74,90,106,122,138].map((x,i)=>`<path d="M${x} 140 Q${x-17} ${96-i%2*13} ${x-4} ${54+i%3*9} Q${x+13} 97 ${x+8} 140Z"/>`).join("")}</g></svg>`;
if(name==="สาหร่าย")return `<svg ${V}>${shadow}<path d="M52 140 Q25 103 54 57 Q78 97 63 140Z" fill="#3fa96d"/><path d="M88 140 Q59 82 91 35 Q113 92 100 140Z" fill="#54bd7a"/><path d="M122 140 Q98 103 132 65 Q148 108 132 140Z" fill="#359866"/><circle cx="42" cy="72" r="5" fill="#c6f4ef" opacity=".8"/><circle cx="133" cy="43" r="7" fill="#c6f4ef" opacity=".8"/></svg>`;
if(name==="กระต่าย")return `<svg ${V}>${shadow}<ellipse cx="90" cy="107" rx="48" ry="34" fill="#d8c6b4"/><ellipse cx="68" cy="39" rx="13" ry="37" fill="#d8c6b4" transform="rotate(-9 68 39)"/><ellipse cx="111" cy="39" rx="13" ry="37" fill="#d8c6b4" transform="rotate(9 111 39)"/><ellipse cx="68" cy="40" rx="6" ry="27" fill="#e9aeb0"/><ellipse cx="111" cy="40" rx="6" ry="27" fill="#e9aeb0"/><circle cx="90" cy="72" r="36" fill="#e0cfbd"/><circle cx="77" cy="68" r="6" fill="#202a29"/><circle cx="103" cy="68" r="6" fill="#202a29"/><circle cx="75" cy="65" r="2" fill="white"/><circle cx="101" cy="65" r="2" fill="white"/><ellipse cx="90" cy="81" rx="6" ry="4" fill="#b8797a"/><circle cx="139" cy="106" r="15" fill="#f0e6dc"/></svg>`;
if(name==="กบ")return `<svg ${V}>${shadow}<ellipse cx="90" cy="110" rx="52" ry="30" fill="#65b85b"/><circle cx="90" cy="76" r="37" fill="#72c565"/><circle cx="69" cy="52" r="14" fill="#78ca69"/><circle cx="111" cy="52" r="14" fill="#78ca69"/><circle cx="69" cy="51" r="7" fill="#172522"/><circle cx="111" cy="51" r="7" fill="#172522"/><circle cx="67" cy="48" r="2" fill="white"/><circle cx="109" cy="48" r="2" fill="white"/><path d="M75 87 Q90 98 105 87" fill="none" stroke="#28543b" stroke-width="4" stroke-linecap="round"/><ellipse cx="43" cy="126" rx="25" ry="9" fill="#58a94f"/><ellipse cx="137" cy="126" rx="25" ry="9" fill="#58a94f"/></svg>`;
if(name==="งู")return `<svg ${V}>${shadow}<path d="M35 119 C38 77 93 145 132 104 C154 81 132 61 115 72" fill="none" stroke="#68a94e" stroke-width="27" stroke-linecap="round"/><ellipse cx="116" cy="70" rx="25" ry="20" fill="#77b95a"/><circle cx="124" cy="65" r="4" fill="#17231e"/><circle cx="125" cy="64" r="1.5" fill="white"/><path d="M139 74 l13 4 -13 3" fill="#df5d66"/></svg>`;
if(name==="เหยี่ยว")return `<svg ${V}>${shadow}<ellipse cx="90" cy="93" rx="34" ry="43" fill="#8b6745"/><path d="M68 83 Q32 47 20 72 Q42 116 74 111Z" fill="#79583d"/><path d="M112 83 Q148 47 160 72 Q138 116 106 111Z" fill="#79583d"/><circle cx="90" cy="57" r="29" fill="#a6815b"/><path d="M84 65 L116 70 L91 82Z" fill="#e5b73f"/><circle cx="79" cy="54" r="5" fill="#17231e"/><circle cx="101" cy="54" r="5" fill="#17231e"/><circle cx="78" cy="52" r="1.5" fill="white"/><circle cx="100" cy="52" r="1.5" fill="white"/><path d="M76 133 l-12 13 M86 133 l-5 14 M104 133 l5 14 M114 133 l12 13" stroke="#e0b23d" stroke-width="5" stroke-linecap="round"/></svg>`;
if(name==="ปลา")return `<svg ${V}>${shadow}<path d="M48 91 L17 62 L17 120 Z" fill="#4c94bd"/><ellipse cx="96" cy="91" rx="60" ry="39" fill="#5eb4d4"/><path d="M79 57 Q98 28 116 58Z" fill="#438daf"/><path d="M83 124 Q103 147 120 119Z" fill="#438daf"/><circle cx="128" cy="80" r="7" fill="#17252a"/><circle cx="126" cy="77" r="2.5" fill="white"/><path d="M145 96 Q153 101 145 106" fill="none" stroke="#28627a" stroke-width="3"/><path d="M68 78 Q91 92 68 105" fill="#79c9df" opacity=".8"/></svg>`;
return `<svg ${V}>${shadow}<circle cx="90" cy="85" r="45" fill="#7dbb77"/></svg>`;
}
function panel(x,cl=""){ui.innerHTML=`<section class="panel ${cl}">${x}</section>`}
function start(){panel(`<div class="title">ภารกิจพิทักษ์ระบบนิเวศ</div><div class="subtitle">ทุกโต๊ะมีโอกาสเป็นฮีโร่ของระบบนิเวศ!</div><div style="height:22vh"></div><button class="btn" onclick="setup()">เริ่มภารกิจ</button>`,"transparent")}
function setup(){panel(`<h1>เลือกจำนวนโต๊ะ</h1><div class="setup">${[6,8,10,12].map(n=>`<button class="btn blue" onclick="names(${n})">${n} โต๊ะ</button>`).join("")}</div>`)}
function names(n){teams=Array.from({length:n},(_,i)=>({name:`โต๊ะ ${i+1}`,score:0}));panel(`<h1>ตั้งชื่อทีมของนักสำรวจ</h1><div class="namegrid">${teams.map((t,i)=>`<input id="n${i}" value="${t.name}">`).join("")}</div><button class="btn green" onclick="saveNames()">เข้าสู่โลกผจญภัย</button>`)}
function saveNames(){teams.forEach((t,i)=>t.name=document.querySelector("#n"+i).value.trim()||t.name);hud.classList.remove("hidden");updateHud();wheelScreen()}
function updateHud(){scoreBox.innerHTML=teams.map((t,i)=>`<div class="scorechip ${i===active?"active":""}"><small>${t.name}</small>${t.score} คะแนน</div>`).join("")}
function wheelScreen(){active=-1;updateHud();panel(`<h1 class="missionTitle">ถึงเวลาสุ่มโต๊ะนักสำรวจ</h1><div class="wheelWrap"><div class="pointer"></div><canvas id="wheelCanvas" width="500" height="500"></canvas></div><button class="btn" id="spinBtn" onclick="spin()">หมุนวงล้อเลือกโต๊ะ</button>`);drawWheel(angle)}
function drawWheel(rot=0){let c=document.querySelector("#wheelCanvas");if(!c)return;let x=c.getContext("2d"),n=teams.length,r=235,cx=250,cy=250;x.clearRect(0,0,500,500);x.save();x.translate(cx,cy);x.rotate(rot);for(let i=0;i<n;i++){let a=i*2*Math.PI/n,b=(i+1)*2*Math.PI/n;x.beginPath();x.moveTo(0,0);x.arc(0,0,r,a,b);x.closePath();x.fillStyle=COLORS[i];x.fill();x.strokeStyle="#fff8";x.lineWidth=4;x.stroke();x.save();x.rotate((a+b)/2);x.translate(135,0);x.rotate(Math.PI/2);x.fillStyle="white";x.font="bold 25px Tahoma";x.textAlign="center";x.shadowColor="#000";x.shadowBlur=4;x.fillText(teams[i].name,0,8);x.restore()}x.restore();x.beginPath();x.arc(cx,cy,78,0,Math.PI*2);x.fillStyle="#18382d";x.fill();x.strokeStyle="#ffe277";x.lineWidth=8;x.stroke();x.fillStyle="#fff";x.font="bold 20px Tahoma";x.textAlign="center";x.fillText("ใครจะได้ตอบ?",cx,cy+7)}
function spin(){document.querySelector("#spinBtn").disabled=true;let target=Math.floor(Math.random()*teams.length),n=teams.length,seg=2*Math.PI/n;let desired=-(target+.5)*seg;let startA=angle,end=desired+Math.PI*2*6;let st=performance.now(),dur=2600;function f(now){let p=Math.min(1,(now-st)/dur),e=1-Math.pow(1-p,4);angle=startA+(end-startA)*e;drawWheel(angle);if(p<1)requestAnimationFrame(f);else{active=target;angle=desired;updateHud();setTimeout(()=>selected(),300)}}requestAnimationFrame(f)}
function selected(){spark();panel(`<div class="subtitle">โต๊ะที่ได้สิทธิ์ตอบ</div><div class="result">${teams[active].name}!</div><div style="height:15vh"></div><button class="btn green" onclick="newQuestion()">เปิดภารกิจลับ</button>`)}
function newQuestion(){if(used.length===questions.length)used=[];let ids=questions.map((_,i)=>i).filter(i=>!used.includes(i)),id=ids[Math.floor(Math.random()*ids.length)];used.push(id);currentQ=questions[id];let opts=[...currentQ.o].sort(()=>Math.random()-.5);panel(`<div class="missionTitle">ภารกิจของ ${teams[active].name}</div><div class="question">${currentQ.q}</div><div class="creatures">${opts.map(n=>{let known=["ต้นไม้","เฟิร์น","หญ้า","สาหร่าย","กระต่าย","กบ","งู","เหยี่ยว","ปลา"].includes(n);return `<div class="creature ${known?"":"textchoice"}">${known?`<div class="model">${svg(n)}</div>`:`<div class="choiceMark">?</div>`}<div class="name">${n}</div></div>`}).join("")}</div><div style="margin-top:18px"><button class="btn green" onclick="judge(true)">ตอบถูก</button><button class="btn red" onclick="judge(false)">ตอบผิด</button></div>`)}
function randomPoints(ok){let a=ok?[10,10,20,20,30,40,50,60,80,100,-10]:[0,0,0,-10,-10,-20,-30,10];return a[Math.floor(Math.random()*a.length)]}
function judge(ok){let p=randomPoints(ok);teams[active].score+=p;updateHud();if(ok)spark();let cls=p>0?"positive":p<0?"negative":"zero",sign=p>0?"+":"";panel(`<div class="result">${ok?"ตอบถูก!":"ยังไม่ถูก"}</div><div class="explain">คำตอบ: <b>${currentQ.a}</b><br>${currentQ.e}</div><div class="subtitle">กล่องพลังงานสุ่มของรอบนี้</div><div class="delta ${cls}">${sign}${p} คะแนน</div><p>${p<0?"โอ๊ะ! เจอพลังงานปั่นป่วน คะแนนลดลง แต่ภารกิจยังไปต่อได้!":p===0?"รอบนี้ไม่เพิ่มและไม่ลดคะแนน":"รับพลังงานเพิ่มให้ทีม!"}</p><button class="btn" onclick="wheelScreen()">หมุนเลือกโต๊ะรอบต่อไป</button>`)}
function endGame(){let rank=[...teams].sort((a,b)=>b.score-a.score);panel(`<div class="title">ภารกิจสำเร็จ!</div><div class="subtitle">ทุกโต๊ะช่วยกันเรียนรู้จนระบบนิเวศกลับมาสมดุล!</div><div class="rank">${rank.map((t,i)=>`<div class="rankrow"><span>อันดับ ${i+1}　${t.name}</span><span>${t.score} คะแนน</span></div>`).join("")}</div><button class="btn" onclick="location.reload()">เริ่มเกมใหม่</button>`,"transparent")}
function spark(){let fx=document.querySelector("#fx");for(let i=0;i<45;i++){let s=document.createElement("i");s.className="spark";s.style.left="50%";s.style.top="45%";s.style.setProperty("--x",(Math.random()*900-450)+"px");s.style.setProperty("--y",(Math.random()*650-325)+"px");fx.appendChild(s);setTimeout(()=>s.remove(),1200)}}
// procedural low-poly nature scene
const cv=document.querySelector("#world"),ctx=cv.getContext("2d");let W,H,t=0;
function resize(){W=cv.width=innerWidth*devicePixelRatio;H=cv.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);W=innerWidth;H=innerHeight}addEventListener("resize",resize);resize();
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(...points[0]);points.slice(1).forEach(p=>ctx.lineTo(...p));ctx.closePath();ctx.fill()}
function scene(){t+=.01;let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#72c9ea");g.addColorStop(.55,"#c7e6c1");g.addColorStop(.56,"#68a85a");g.addColorStop(1,"#315e3c");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
poly([[0,H*.58],[W*.18,H*.29],[W*.34,H*.58]],"#698d78");poly([[W*.18,H*.58],[W*.48,H*.22],[W*.72,H*.58]],"#5d806f");poly([[W*.58,H*.58],[W*.82,H*.31],[W,H*.56],[W,H*.7]],"#638a72");
poly([[W*.18,H*.29],[W*.25,H*.38],[W*.12,H*.39]],"#dce6d8");poly([[W*.48,H*.22],[W*.55,H*.33],[W*.4,H*.34]],"#e8eee6");
ctx.fillStyle="#55a8c7";ctx.beginPath();ctx.moveTo(W*.62,H*.55);ctx.bezierCurveTo(W*.58,H*.67,W*.72,H*.73,W*.58,H);ctx.lineTo(W*.78,H);ctx.bezierCurveTo(W*.85,H*.75,W*.7,H*.67,W*.72,H*.55);ctx.fill();
for(let i=0;i<12;i++){let x=(i*137%W),base=H*(.58+(i%4)*.09),s=35+(i%3)*15;ctx.fillStyle="#654a31";ctx.fillRect(x,base-s*.4,10,s*.7);let sway=Math.sin(t+i)*3;poly([[x-28+sway,base-s*.35],[x+5,base-s*1.25],[x+38+sway,base-s*.35]],i%2?"#2f7c48":"#3d8e4e")}
for(let i=0;i<7;i++){let x=(i*211+80)%W,y=H*.22+(i%3)*55+Math.sin(t*2+i)*10;ctx.fillStyle="#263d37";ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+16,y-7);ctx.lineTo(x+9,y+2);ctx.lineTo(x+20,y+6);ctx.lineTo(x,y+4);ctx.fill()}
requestAnimationFrame(scene)}scene();start();